/**
 * Predefined tech stack options for multiselect
 */
export const TECH_STACK_OPTIONS = [
	// Frontend Frameworks & Libraries
	'React',
	'Next.js',
	'Vue.js',
	'Angular',
	'Svelte',
	'TypeScript',
	'JavaScript',
	'HTML5',
	'CSS3',
	'Sass',
	'SCSS',
	'Tailwind CSS',
	'Bootstrap',
	'Material UI',
	'Ant Design',
	'Chakra UI',
	'Kendo UI',
	'Styled Components',
	'Emotion',
	
	// State Management
	'Redux',
	'Zustand',
	'MobX',
	'Jotai',
	'Recoil',
	'Context API',
	
	// 3D & Visualization
	'Three.js',
	'WebGL',
	'D3.js',
	'Chart.js',
	'Recharts',
	
	// Backend
	'Node.js',
	'Express',
	'NestJS',
	'Fastify',
	'ASP.NET Core',
	'.NET Framework',
	'.NET Core',
	'C#',
	'Python',
	'Django',
	'Flask',
	'FastAPI',
	'Java',
	'Spring Boot',
	'Go',
	'Rust',
	'PHP',
	'Laravel',
	
	// Mobile
	'React Native',
	'Ionic',
	'Flutter',
	'Swift',
	'Kotlin',
	
	// Desktop
	'WPF',
	'WinForms',
	'Electron',
	'Tauri',
	
	// Databases
	'MySQL',
	'PostgreSQL',
	'MSSQL',
	'SQL Server',
	'MongoDB',
	'Redis',
	'SQLite',
	'Firebase',
	'Supabase',
	
	// ORMs & Database Tools
	'Entity Framework Core',
	'EF Core',
	'Dapper',
	'Prisma',
	'TypeORM',
	'Sequelize',
	'Mongoose',
	
	// Authentication & Authorization
	'Auth0',
	'Keycloak',
	'Azure AD',
	'Firebase Auth',
	'JWT',
	'OAuth',
	'Passport.js',
	
	// APIs & Data
	'REST API',
	'GraphQL',
	'gRPC',
	'WebSocket',
	'Apollo',
	'React Query',
	'SWR',
	
	// DevOps & Cloud
	'Azure',
	'AWS',
	'Google Cloud',
	'Docker',
	'Docker Compose',
	'Kubernetes',
	'Jenkins',
	'GitHub Actions',
	'GitLab CI/CD',
	'CircleCI',
	'Netlify',
	'Vercel',
	'Heroku',
	
	// Version Control
	'Git',
	'GitHub',
	'GitLab',
	'Bitbucket',
	
	// Testing
	'Jest',
	'Vitest',
	'Cypress',
	'Playwright',
	'React Testing Library',
	'Enzyme',
	
	// Build Tools
	'Webpack',
	'Vite',
	'Parcel',
	'Rollup',
	'ESBuild',
	
	// Architecture Patterns
	'Clean Architecture',
	'CQRS',
	'MVVM',
	'MVC',
	'Microservices',
	'Serverless',
	'IoC',
	'Dependency Injection',
	
	// Agile & Project Management Methodologies
	'Scrum',
	'Kanban',
	'Lean',
	'Agile',
	'Extreme Programming (XP)',
	'SAFe',
	'LeSS',
	'Nexus',
	'Spotify Model',
	'Waterfall',
	'Hybrid Methodology',
	'DevOps',
	'CI/CD',
	'Continuous Integration',
	'Continuous Deployment',
	'Continuous Delivery',
	
	// Development Practices
	'TDD',
	'Test-Driven Development',
	'BDD',
	'Behavior-Driven Development',
	'DDD',
	'Domain-Driven Design',
	'Pair Programming',
	'Mob Programming',
	'Code Review',
	'Peer Review',
	'Refactoring',
	'Technical Debt Management',
	'Code Documentation',
	'API Documentation',
	'Technical Writing',
	
	// Quality Assurance Practices
	'QA Testing',
	'Manual Testing',
	'Automated Testing',
	'Integration Testing',
	'End-to-End Testing',
	'Performance Testing',
	'Load Testing',
	'Security Testing',
	'Penetration Testing',
	'User Acceptance Testing',
	'Regression Testing',
	
	// Business & Process Practices
	'Design Thinking',
	'User-Centered Design',
	'Lean Startup',
	'Design Sprints',
	'User Story Mapping',
	'Retrospectives',
	'Sprint Planning',
	'Daily Standups',
	'Product Backlog Management',
	'Stakeholder Management',
	
	// Developer IDEs & Editors
	'VS Code',
	'Visual Studio',
	'IntelliJ IDEA',
	'PyCharm',
	'WebStorm',
	'PhpStorm',
	'Rider',
	'Android Studio',
	'Xcode',
	'Sublime Text',
	'Vim',
	'Neovim',
	'Emacs',
	'Atom',
	'Brackets',
	
	// Developer Tools
	'Postman',
	'Insomnia',
	'Chrome DevTools',
	'Firefox DevTools',
	'Browser DevTools',
	'Charles Proxy',
	'Fiddler',
	'Terminal',
	'PowerShell',
	'Bash',
	'Zsh',
	
	// Package Managers & Build Tools
	'NPM',
	'Yarn',
	'PNPM',
	'Bun',
	'Pip',
	'Conda',
	'Maven',
	'Gradle',
	'NuGet',
	'Composer',
	
	// Code Quality & Formatting
	'ESLint',
	'Prettier',
	'SonarQube',
	'Stylelint',
	'Biome',
	
	// Office Productivity - Microsoft Office
	'Microsoft Word',
	'Microsoft Excel',
	'Microsoft PowerPoint',
	'Microsoft Outlook',
	'Microsoft Teams',
	'Microsoft OneNote',
	'Microsoft OneDrive',
	'Microsoft SharePoint',
	'Microsoft Project',
	'Microsoft Visio',
	'Microsoft Access',
	'Microsoft Power BI',
	'Microsoft Power Automate',
	'Microsoft Power Apps',
	'Microsoft Forms',
	'Microsoft Planner',
	'Microsoft To Do',
	'Microsoft Lists',
	'Microsoft Sway',
	'Microsoft Publisher',
	
	// Office Productivity - Google Workspace
	'Google Docs',
	'Google Sheets',
	'Google Slides',
	'Gmail',
	'Google Drive',
	'Google Calendar',
	'Google Meet',
	'Google Chat',
	'Google Workspace',
	'Google Forms',
	'Google Sites',
	'Google Keep',
	'Google Tasks',
	'Google Analytics',
	'Google Search Console',
	
	// Collaboration & Communication
	'Slack',
	'Discord',
	'Zoom',
	'Webex',
	'Skype',
	'Loom',
	'Miro',
	'Mural',
	'Whiteboard',
	
	// Project Management
	'Asana',
	'Trello',
	'Monday.com',
	'ClickUp',
	'Jira',
	'Basecamp',
	'Airtable',
	'Smartsheet',
	'Linear',
	'Shortcut',
	
	// CRM & Sales
	'Salesforce',
	'HubSpot',
	'Zoho CRM',
	'Pipedrive',
	'ActiveCampaign',
	'Mailchimp',
	
	// Data Analytics & Business Intelligence
	'Tableau',
	'Mixpanel',
	'Amplitude',
	'Looker',
	'Qlik',
	'Metabase',
	'Apache Superset',
	'Excel Analytics',
	
	// Design & Creative Tools
	'Figma',
	'Adobe Photoshop',
	'Adobe Illustrator',
	'Adobe InDesign',
	'Adobe XD',
	'Adobe Premiere Pro',
	'Adobe After Effects',
	'Canva',
	'Sketch',
	'Framer',
	'InVision',
	
	// Documentation & Note-Taking
	'Notion',
	'Confluence',
	'Obsidian',
	'Roam Research',
	'LogSeq',
	'Bear',
	'Evernote',
	'Markdown',
	'Wiki',
	
	// Email & Marketing
	'Constant Contact',
	'HubSpot Email',
	'Outreach',
	'Salesforce Marketing Cloud',
	
	// Accounting & Finance
	'QuickBooks',
	'Xero',
	'FreshBooks',
	'Sage',
	'Excel Financial Modeling',
]
